### ISSUE TITLE
Caching issues with tutorial

### ISSUE THREAD

**Issue by craic** [Polymer/polymer-tutorial#4]
I'm following the tutorial using Chrome 35.0.1916.114 on Mac OS X 10.9.3 and serving the pages with 'python -m SimpleHTTPServer' to url http://localhost:8000/step-3/

The styles appear to be cached such that changing any of them and reloading the browser window results in no change. Opening an Incognito window and going to the url gets me the result I expect, so the problem is caching... but where...

Is this a function of the python web server (I have not used it before) or is it a Web Components/Shadow Dom issue in the browser ? 

thanks

**Comment by andresetevejob** [comment]
Hi All,
I have the same problem.Somebody can me say, how to solve this?

**Comment by programulya** [comment]
And I have the same problem

**Comment by robdodson** [comment]
The reason you're seeing this is because Chrome heavily caches HTML Imports (it's trying to do the right thing and give you a performant experience). The solution is to open the devtools and check the box which disables the cache while the devtools are open.

**Comment by programulya** [comment]
What about production environment? Adding version "?v=" in all Polymer HTML imports doesn't solve this.

**Comment by mbergeron** [comment]
Rob, it's true that disabling the cache in the devtools fix the caching problem. But what about production? The only way I found out so far is to vulcanize the whole thing. and adding a fake version to it. Is this the only solution?

Thanks

**Comment by tuespetre** [comment]
@mbergeron 

Vulcanizing + versioning is a performant approach. If you don't want to Vulcanize, and especially if the majority of your app's usage will be HTTP2-enabled, you could always set up cache headers for your server like: `Cache-Control: max-age=0, must-revalidate`

**Comment by robdodson** [comment]
@programulya I would imagine you would only add a cache busting query string ( `?v=123...` ) to your final vulcanized bundle.

**Comment by ghost** [comment]
FYI if clearing the cache doesn't work, you may have to clear your cookies too.

**Comment by reads** [comment]
this is genuinely annoying and really stupid. why is it so hard to replace the cache locally? "clear cache and reload" should do just that, shouldn't it?

**Comment by robdodson** [comment]
You shouldn't need to clear your cookies I don't think
